services:
  gh_issues_contributors_backend_test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        MIX_ENV: test
    environment:
      MIX_ENV: test
    env_file:
      - .env.test
    depends_on:
      - db_test
    volumes:
      - .:/app
    command: >
      sh -c "mix deps.get && mix test --trace" 
    networks:
      - admin

  db_test:
    image: postgres:13.5
    container_name: gh_issues_contributors_test
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gh_issues_contributors_dev
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - admin
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

networks:
  admin:
    name: admin

volumes:
  postgres_test_data: