services:
  gh_issues_contributors:
    stdin_open: true
    tty: true
    build:
      context: .
      target: build
      args:
        MIX_ENV: ${MIX_ENV}
    container_name: gh_issues_contributors
    command: iex -S mix phx.server
    restart: unless-stopped
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - admin
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    depends_on:
      - db

  db:
    image: postgres:13.5
    container_name: gh_issues_contributors_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: gh_issues_contributors
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - admin
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

networks:
  admin:
    name: admin

volumes:
  postgres_data: